### ISSUE TITLE
sep31 second customer put use a empty memo 

### ISSUE THREAD

**Issue by wenhao888** [stellar/django-polaris#426] opened 2021-05-23 19:14 UTC
### What version are you using?
i am using polaris 1.4.1

### What did you do?
i am testing sep-31 workflow to send asset from demo-wallet to my local running anchor-server. 
in demo-wallet, i see the following flow.
1. get /customer.
 server returns "root":{2 items
"status":"NEEDS_INFO"
"fields":{3 items
"email_address":{...}4 items
"id_type":{...}4 items
"photo_id_front":{...}3 items
}
}

2.  i then input user information in the ui. and i see wallet sent the following information to polaris server using put /customer
root":{6 items
"account":"GBFZOC4UL4Y47PI..."
"memo_type":"hash"
"memo":"YsgDF7Q+aseRGhg..."
"email_address":"wenhao.lin@gmai..."
"id_type":"Passport"
"photo_id_front":"12"
3. i see server responded
"root":{1 item
"id":"11838dea-c139-4..."
}
4. now i see the second put /customer
"root":{3 items
"account":"GBFZOC4UL4Y47PI..."
"memo_type":"hash"
"memo":""
}
5. and server returns 
"root":{1 item
"error":"invalid 'memo' for 'memo_type'"
}

### What did you expect to see?
no error message in demo-wallet

### What did you see instead?
i see error message "error":"invalid 'memo' for 'memo_type'"

**Comment by yuriescl** [comment] 2021-05-23 20:30
@wenhao888 When `memo_type` is `hash`, `memo` must contain a valid base64 hash. In your case it's an empty string, that's why you're getting the error.

**Comment by wenhao888** [comment] 2021-05-23 21:00
i totally agree. I am using stellar demo wallet for the testing.  I see the client's behavior is not consistent with sep-12 and sep-31.
1) the wallet called get /customer ?type=sep31-sender. but did not called this endpoint for the receiver. 
2) of course, its send the empty hash for the receiver when calling put /customer for the receiver.

**Comment by yuriescl** [comment] 2021-05-24 12:02
>     2. of course, its send the empty hash for the receiver when calling put /customer for the receiver.

I was able to reproduce this. The demo wallet sends an empty memo when calling PUT for the receiver customer.
This issue might belong to https://github.com/stellar/stellar-demo-wallet

**Comment by JakeUrban** [comment] 2021-05-24 17:16
I'm not able to reproduce this when using testanchor.stellar.org's SEP-31 integration, I see the demo wallet using a valid hash memo for the receiving customer. 

Based on what @wenhao888 has outlined, it seems like another issue is that the demo wallet doesn't report response failures from the anchor server like it should. I'll file an issue on the demo wallet for this.

**Comment by wenhao888** [comment] 2021-05-24 17:36
i debugged the demo-wallet code. the problem happened in the following scenario:
when sender has only one type, and the receiver has multiple types; or vice versa. 
The code having issue is Sep31Send.tsx. I made the following change, 

dispatch(
      setCustomerTypesAction({ senderType: sender || data.senderType ||"", receiverType: receiver || data.receiverType||""}),
    );

problem solved.

**Comment by JakeUrban** [comment] 2021-08-05 16:59
Closing because this is an issue with the demo wallet, not Polaris.

**Closed by JakeUrban** 2021-08-05 16:59 UTC
Labels: bug
