### ISSUE TITLE
Add pending_external transactions to poll_pending_deposits list

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#324] opened 2020-10-04 16:30 UTC
Polaris [currently calls](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/poll_pending_deposits.py#L150) `rri.poll_pending_deposits()` only for transactions with status `pending_user_transfer_start`.
But, some Anchors might wanna set the status as `pending_external` when the funds are received from the user and also require some extra step before returning the transaction from `rri.poll_pending_deposits()`.
For example, if it's a Bitcoin deposit, the user sends the funds to an account (so the funds are received), but the Anchor has to send the funds to its own Bitcoin account, which can take a few minutes, so the correct status would be `pending_external` since we're not exactly waiting for the user to transfer funds.

This is the flow Polaris currently supports:

deposits with status `pending_user_transfer_status` -> passed to `rri.poll_pending_deposits()` -> anchor can maybe add it to the list returned so Polaris can execute the deposit transaction

This is the flow I'd like to have:

1. deposits with status `pending_user_transfer_status` -> passed to `rri.poll_pending_deposits()` -> anchor sets status as `pending_external` but does not add it to the list returned
2. deposits with status `pending_external` -> passed to `rri.poll_pending_deposits()` -> anchor can maybe add it to the list returned so Polaris can execute the deposit transaction

I imagine this would require an extra management command plus an integration function.
This would be similar to `poll_outgoing_transactions` but for deposits.

**Comment by yuriescl** [comment] 2020-10-04 16:33
This idea is applicable if you assume that `pending_user_transfer_status` is not a suitable status for that intermediate step, which is after receiving the funds from the user and before receiving the funds in the anchor account.

**Comment by yuriescl** [comment] 2020-10-04 16:39
Or maybe `rri.poll_pending_deposits()` can receive transactions with status `pending_external` as well, and the Anchor can just check the transaction status inside the function to decide how to handle it.

**Comment by JakeUrban** [comment] 2020-10-07 00:09
> But, some Anchors might wanna set the status as pending_external when the funds are received from the user and also require some extra step before returning the transaction from rri.poll_pending_deposits()

So `pending_external` is actually not the appropriate status here, it is `pending_anchor`. The deposit is in fact received, but you need to do more things before it is ready to be submitted.

So the question becomes, how can we change the `poll_pending_deposits` flow to allow deposit transactions to be `pending_anchor` after `pending_user_transfer_start`.

The reality is that you could return transactions that are not passed to the function. This is not ideal because you would think all transactions that _could_ be passed _would_ be passed, but still. If you look at the actual function that checks if a transaction is ready to go before submitting looks like this:
```
def execute_deposit(transaction: Transaction) -> bool:
    valid_statuses = [
        Transaction.STATUS.pending_user_transfer_start,
        Transaction.STATUS.pending_anchor,
    ]
    if transaction.kind != transaction.KIND.deposit:
        raise ValueError("Transaction not a deposit")
    elif transaction.status not in valid_statuses:
        raise ValueError(
            f"Unexpected transaction status: {transaction.status}, expecting "
            f"{' or '.join(valid_statuses)}."
        )
    if transaction.status != Transaction.STATUS.pending_anchor:
        transaction.status = Transaction.STATUS.pending_anchor
```

**Comment by JakeUrban** [comment] 2020-10-07 00:11
We already allow transactions to be in the `pending_anchor` state when submitting.

So, short term solution: just return `pending_anchor` transactions that are ready but were not passed to the function.

Long term, we should include the `pending_anchor` deposits to `poll_pending_deposits()`. The problem is that this kinda get in the way of how multisig transactions are detected in Polaris right now, so it requires more thinking.

**Comment by yuriescl** [comment] 2020-10-07 13:02
> So pending_external is actually not the appropriate status here, it is pending_anchor

That's correct. For me, Polaris is using `pending_anchor` as "pending Stellar operation", and Bitcoin is an external network, that's why I thought it wasn't the proper status.
`pending_external` is more like "pending rails operation, rails being an entity between the Anchor and the user", and this status seemed more appropriate for that Bitcoin transaction.

I do agree, though, that `pending_anchor` would make more sense due to its name, but it's currently being used to indicate pending Stellar operations. I'm not sure if it's worth adapting Polaris to deal with the ambiguity that this change would introduce, since the same status could also mean "pending an operation on another crypto network - or something like that".

**Comment by JakeUrban** [comment] 2020-10-14 18:07
`pending_external` is currently used by deposits when the anchor can detect that the off-chain inbound payment is pending the off-chain rails processing. It sounds like you may be able to do that with detecting incoming BTC payments. 

`pending_anchor` is a different status that should be used for all other non-external processing. Polaris will fix its sensitivity to `pending_anchor`, that way anchors can mark _received_ deposits as `pending_anchor` without being submitted to Stellar.

So in your case, it sounds like `pending_external` is relevant and useful, but `pending_anchor` should be used when you're doing processing and not waiting on the BTC network. The transaction should not be in `pending_external` if the funds have been received.

Give me a bit to figure out how I can redesign Polaris to allow anchors to use `pending_anchor` on deposits.

**Comment by JakeUrban** [comment] 2020-10-14 18:44
So there are two changes that I think could help support your use case:

- Adding `pending_external` transactions to the list passed to `poll_pending_deposits()`

This will happen regardless of the approach we take for the next change:

- Adding a clear way for anchors to specify if a multisig transaction is ready to be submitted

Originally I thought `poll_pending_deposits()` could return both normal and multisig transactions, but `poll_pending_deposits()` is really for polling external systems on the state of incoming deposits, not returning already-received multisig transactions.

So, one way we could do this is by adding another `DepositIntegration.ready_multisig_transactions()` integration function that would be called alongside `poll_pending_deposits`.

Another way would be to add an explicit `multisig` boolean field to the `Transaction` object so Polaris could query for ready multisig transactions like so:
```
Transaction.objects.filter(
        kind=Transaction.KIND.deposit,
        multisig=True,
        pending_signatures=False,
        envelope_xdr__isnull=False,
).exclude(
    status__in=[Transaction.STATUS.completed, Transaction.STATUS.error]
)
```

This would return the multisig deposit transactions that have not completed and are not pending signatures for an envelope that exists, AKA its ready for submission. If it wasn't ready, the anchor should not have marked the `pending_signatures` status to `False`. Keep in mind the transaction's status column is likely `pending_anchor` while `pending_signatures=True`.

**Comment by yuriescl** [comment] 2020-10-14 20:44
@JakeUrban This is becoming a bit confusing, and I'm starting to think those changes are a bad idea because:
- It would either require a new field or a new integration function, this can add unnecessary complexity and make it more difficult for Anchors to understand the status flow.
- It sounds that the ideal solution would be to add a new status, but I imagine that's outside the scope of Polaris since it should have only the statuses listed in the SEPs. Also, the scenario we're trying to support might not even be that common.

I think `pending_external` is the proper status for this. So the only change needed in Polaris would be to pass `pending_external` transactions to `poll_pending_deposits()`. It's on the Anchor to figure out what `pending_external` means in that situation.
Polaris could then treat `pending_external` as the "Anchor is dealing with the transaction by itself and Polaris should not do anything with the transation until it's returned from `poll_pending_deposits()`".

**Comment by yuriescl** [comment] 2020-10-14 20:48
@JakeUrban Updated by comment

**Comment by JakeUrban** [comment] 2020-10-14 21:06
I'll include `pending_external` transaction when passing them to `poll_pending_deposits()`. Polaris doesn't modify or take any action on `pending_external` transactions today.

**Comment by JakeUrban** [comment] 2020-11-24 19:17
I completely forgot about this issue because I never assigned it to myself, my bad. I'll get on this today.

**Closed** 2020-11-25 20:22 UTC
Labels: discussion
